FROM ruby:3.1.4

# 必要なパッケージのインストール
RUN apt-get update -qq && apt-get install -y \
    nodejs npm default-mysql-client build-essential default-libmysqlclient-dev

# 作業ディレクトリの設定
WORKDIR /rails

# Gemfileをコピーしてbundle install
COPY Gemfile Gemfile.lock ./
RUN bundle install

# アプリケーションファイルをコピー
COPY . .

# ポート3000を公開
EXPOSE 3000

# Rails サーバーを起動
CMD ["rails", "server", "-b", "0.0.0.0"]